---
solr_collections:
  - name: finding-aid-discovery
    configset: finding-aid-discovery
    replicas: 3
    shards: 3

solr_configsets:
  - name: "finding-aid-discovery"
    path: "roles/finding_aid_discovery/files/src/solr/conf/"

solr_docker_image_tag: 9.3.0

solr_limits_cpu: 2
solr_limits_mem: "8G"

solr_proxy_host: "finaid-stg01.library.upenn.int"

solr_custom_env_variables:
  SOLR_HEAP: "6G"
  SOLR_JAVA_MEM: "-Xms4G -Xmx4G"
